### ISSUE TITLE
Dúvidas / Sugestões

### ISSUE THREAD

**Issue by tiagoprn** [btmluiz/lbdev-chat#3]
- <https://github.com/btmluiz/lbdev-chat/blob/master/api/serializers.py#L19>:  no python 3, `super().__init__(*args, **kwargs)` seria suficiente. 

 - <https://github.com/btmluiz/lbdev-chat/blob/master/api/serializers.py#L21>: uma forma mais sucinta de escrever `if fields is not None:` seria: `if fields`. 

- <https://github.com/btmluiz/lbdev-chat/blob/master/api/serializers.py#L31>: esse método com um pass seria desnecessário, dado que já existe na classe pai e não foi feita nenhuma customização. O mesmo se aplica ao abaixo dele. 

- <https://github.com/btmluiz/lbdev-chat/blob/master/api/serializers.py#L48>  Esta validação poderia ser feita pelo próprio serializer (colocando required=True)

- <https://github.com/btmluiz/lbdev-chat/blob/master/api/serializers.py#L83> Não ficou muito claro a intenção das permissions nesse trecho - está sendo splittado da string de permission 2 vezes e verificando se o output está dentro de permission (se foi splittado de lá, nos parece estar lá dentro :thinking: ) 

- <https://github.com/btmluiz/lbdev-chat/blob/master/chat/models.py#L21> Qual o propósito da chat_key, se o id de Chat já é do mesmo tipo uuid? 

- <https://github.com/btmluiz/lbdev-chat/blob/master/chat/resolvers.py#L20> O que acha de separar os exceptions num arquivo a parte?

- <https://github.com/btmluiz/lbdev-chat/blob/master/chat/resolvers.py#L39> Preciosismo nosso talvez, mas não seria melhor `t` no lugar de `x` no nome da variável, pela semâtica? :thinking: 

- <https://github.com/btmluiz/lbdev-chat/blob/0f8cb979c6ed8ebbbb4ac5295644073de06fec63/lbdev_chat/settings.py#L184> Ficamos curiosos em entender onde é usado o Google Cloud Storage.

**Comment by btmluiz** [comment]
-  https://github.com/btmluiz/lbdev-chat/blob/master/api/serializers.py#L83 A intenção das permission é para que seja agrupado as permissões "change", "view", "add", "delete" por model no caso ficaria algo assim:
`
"permissions": {
    "logentry": [
      "change",
      "view",
      "add",
      "delete"
    ],
    "chathistory": [
      "add",
      "view",
      "change",
      "delete"
    ]
}`
- https://github.com/btmluiz/lbdev-chat/blob/master/chat/models.py#L21 o chat_key acabou sendo redundante nesse caso, e será removido em uma próxima atualização

- https://github.com/btmluiz/lbdev-chat/blob/master/chat/resolvers.py#L39 Sim, foi apenas o costume de utilizar `x` em loop

- https://github.com/btmluiz/lbdev-chat/blob/0f8cb979c6ed8ebbbb4ac5295644073de06fec63/lbdev_chat/settings.py#L184 o Cloud Storage é utilizado a principio para armazenamento de arquivos estáticos, como javascript e css do Swagger e até mesmo do Django Admin, porém o intuito é de utilizar para realizar o armazenamento de arquivos enviado dentro do sistema de troca de mensagens.
